### ISSUE TITLE
'any' can't check function

### ISSUE THREAD

**Issue by joeltankam** [joeltankam/checkif.js#19]
The `any` checker doesn't check if any value is equal to a function, but instead consider the function as a matcher.

There should be a possibility to consider second parameter as a value and not a matcher function.

```js
import { any } from 'checkif.js';

let _function = function (x) { ... };
any({ x: _function, y: ... }, _function); // false
```

**Comment by joeltankam** [comment]
Linked to #13 
Similar issue solved by #18

**Comment by joeltankam** [comment]
@boristane

**Comment by boristane** [comment]
You mean:

```js
import { any } from 'checkif.js';

let _function = function (x) { ... };
any({ x: _function, y: ... }, _function); // true
```
right ? `any` in this case should return `true`...

**Comment by joeltankam** [comment]
It currently returns false, that's what I meant
