### ISSUE TITLE
Check if all elements equal a specific value

### ISSUE THREAD

**Issue by joeltankam** [joeltankam/checkif.js#4]
```js
import { all } from 'if.js';

let array = [0,1,2,3];
all(array, 0); // false
```

**Comment by Argetan** [comment]
How precisely do you want to confirm that the objects match? Would a `==` or `===` suffice or do you want to use a more precise method such as `_.eq(value, other)` from [lo-dash](https://lodash.com/docs/4.17.10#eq)?

**Comment by Argetan** [comment]
I tried putting the `all` function in a file called `if.js` however if you try importing it will throw an error because `if` is a reserved keyword. What do you suggest we rename it to?

**Comment by joeltankam** [comment]
`all` should be imported next to `is` in `index.js`. And the code should be in a separated `all.js` under `src`, same for tests.
